### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by SietseDEV** [RemiixInc/screenshot#2]
I deployed this myself and i get this error when trying to get a screenshot: The server encountered an error. You may have inputted an invalid query.

And my vercel logs give me this error:
```
Error: Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by janbarasek** [comment]
I have same issue. The problem is newest Node version on Vercel.

I dont know how to fix it.
